### ISSUE TITLE
errorHandler  Cannot read properties of undefined (reading 'resetFields')

### ISSUE THREAD

**Issue by snow212-cn** [PingKuNet/aliyunpan#39]
最新版3.19.03 下载功能完全失效

下载文件就报错如题，运行日志：
`errorHandler //== Error ==// Cannot read properties of undefined (reading 'resetFields') //== Stack ===// TypeError: Cannot read properties of undefined (reading 'resetFields') at handleClose (file:///C:/Users/xx/Downloads/Alixby-v3.9.13-beta-win32-x64/resources/app.asar/dist/index.js:158:22032) at Vl (file:///C:/Users/xx/Downloads/Alixby-v3.9.13-beta-win32-x64/resources/app.asar/dist/index.js:1:12680) at bo (file:///C:/Users/xx/Downloads/Alixby...`

**Comment by PingKuNet** [comment]
这个这个下载功能没有做了，同步代码过来后，还没有完善下载功能，原作者的V3下载功能也还没有做好，所以就是结果就是你现在这样喽。
